using System.Collections.Generic;

namespace GamerIntegrity
{
    public static class Rules
    {
        public static List<FileNameRule> FileNameRules()
        {
            return new List<FileNameRule>
            {
                new FileNameRule { Token = @"cheat source", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 90, Score = 80 },
                new FileNameRule { Token = @"cheat src", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 88, Score = 75 },
                new FileNameRule { Token = @"hack source", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 88, Score = 75 },
                new FileNameRule { Token = @"hack src", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 86, Score = 70 },
                new FileNameRule { Token = @"aimbot source", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 92, Score = 85 },
                new FileNameRule { Token = @"aimbot src", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 90, Score = 80 },
                new FileNameRule { Token = @"wallhack source", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 92, Score = 85 },
                new FileNameRule { Token = @"esp source", Category = @"File Name Scan", Label = @"Cheat source/code artifact detected", Severity = Severity.Critical, Confidence = 88, Score = 75 },
                new FileNameRule { Token = @"external cheat", Category = @"File Name Scan", Label = @"Cheat project/source folder detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"internal cheat", Category = @"File Name Scan", Label = @"Cheat project/source folder detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"cheat loader", Category = @"File Name Scan", Label = @"Cheat loader/source artifact detected", Severity = Severity.High, Confidence = 84, Score = 60 },
                new FileNameRule { Token = @"cheat menu", Category = @"File Name Scan", Label = @"Cheat UI/menu artifact detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"cheat overlay", Category = @"File Name Scan", Label = @"Cheat overlay artifact detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"game cheat", Category = @"File Name Scan", Label = @"Cheat project/source folder detected", Severity = Severity.High, Confidence = 84, Score = 60 },
                new FileNameRule { Token = @"cs2 cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"csgo cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"valorant cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"fortnite cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"warzone cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"apex cheat", Category = @"File Name Scan", Label = @"Game cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"external esp", Category = @"File Name Scan", Label = @"Cheat feature/project detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"internal esp", Category = @"File Name Scan", Label = @"Cheat feature/project detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"overlay esp", Category = @"File Name Scan", Label = @"Cheat feature/project detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"box esp", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 50 },
                new FileNameRule { Token = @"skeleton esp", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 50 },
                new FileNameRule { Token = @"driver cheat", Category = @"File Name Scan", Label = @"Kernel cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"kernel cheat", Category = @"File Name Scan", Label = @"Kernel cheat project detected", Severity = Severity.High, Confidence = 86, Score = 65 },
                new FileNameRule { Token = @"dma cheat", Category = @"File Name Scan", Label = @"DMA cheat indicator detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"arduino aimbot", Category = @"File Name Scan", Label = @"External aim-assist tooling detected", Severity = Severity.High, Confidence = 82, Score = 55 },
                new FileNameRule { Token = @"kmbox", Category = @"File Name Scan", Label = @"External input-assist tooling detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"osiris", Category = @"File Name Scan", Label = @"Known public cheat project detected", Severity = Severity.High, Confidence = 78, Score = 45 },
                new FileNameRule { Token = @"nullhooks", Category = @"File Name Scan", Label = @"Known public cheat project detected", Severity = Severity.High, Confidence = 80, Score = 50 },
                new FileNameRule { Token = @"aimtux", Category = @"File Name Scan", Label = @"Known public cheat project detected", Severity = Severity.High, Confidence = 78, Score = 45 },
                new FileNameRule { Token = @"gamesense", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"neverlose", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"onetap", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"fatality", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"primordial", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"legendware", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"interium", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"rifk7", Category = @"File Name Scan", Label = @"Known cheat brand/project detected", Severity = Severity.Medium, Confidence = 70, Score = 30 },
                new FileNameRule { Token = @"hwid spoofer", Category = @"File Name Scan", Label = @"Hardware ID spoofer detected", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"spoofer", Category = @"File Name Scan", Label = @"Spoofer tool/file detected", Severity = Severity.Medium, Confidence = 60, Score = 20 },
                new FileNameRule { Token = @"trace cleaner", Category = @"File Name Scan", Label = @"Trace-cleaner file detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"cleaner", Category = @"File Name Scan", Label = @"Cleaner-related file detected", Severity = Severity.Low, Confidence = 45, Score = 8 },
                new FileNameRule { Token = @"kdmapper", Category = @"File Name Scan", Label = @"Kernel driver mapper detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"driver mapper", Category = @"File Name Scan", Label = @"Kernel driver mapper detected", Severity = Severity.High, Confidence = 75, Score = 40 },
                new FileNameRule { Token = @"manual map", Category = @"File Name Scan", Label = @"Manual mapping tool/file detected", Severity = Severity.Medium, Confidence = 65, Score = 22 },
                new FileNameRule { Token = @"manualmap", Category = @"File Name Scan", Label = @"Manual mapping tool/file detected", Severity = Severity.Medium, Confidence = 65, Score = 22 },
                new FileNameRule { Token = @"injector", Category = @"File Name Scan", Label = @"Injector tool/file detected", Severity = Severity.Medium, Confidence = 60, Score = 20 },
                new FileNameRule { Token = @"loader", Category = @"File Name Scan", Label = @"Loader-related file detected", Severity = Severity.Low, Confidence = 45, Score = 8 },
                new FileNameRule { Token = @"bypass", Category = @"File Name Scan", Label = @"Bypass-related file detected", Severity = Severity.Medium, Confidence = 60, Score = 20 },
                new FileNameRule { Token = @"eac bypass", Category = @"File Name Scan", Label = @"Anti-cheat bypass file detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"battleye bypass", Category = @"File Name Scan", Label = @"Anti-cheat bypass file detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"vanguard bypass", Category = @"File Name Scan", Label = @"Anti-cheat bypass file detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"aimbot", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"wallhack", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"triggerbot", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"ragebot", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 80, Score = 45 },
                new FileNameRule { Token = @"silent aim", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.High, Confidence = 75, Score = 40 },
                new FileNameRule { Token = @"no recoil", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"norecoil", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"radar hack", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"glow hack", Category = @"File Name Scan", Label = @"Cheat feature file/folder detected", Severity = Severity.Medium, Confidence = 65, Score = 25 },
                new FileNameRule { Token = @"cheat engine", Category = @"File Name Scan", Label = @"Cheat Engine memory editor detected", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"cheatengine", Category = @"File Name Scan", Label = @"Cheat Engine memory editor detected", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"wemod", Category = @"File Name Scan", Label = @"WeMod game trainer detected", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"x64dbg", Category = @"File Name Scan", Label = @"Game debugging/disassembly tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"x32dbg", Category = @"File Name Scan", Label = @"Game debugging/disassembly tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"ollydbg", Category = @"File Name Scan", Label = @"Game debugging/disassembly tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"ida", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"ida pro", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 74, Score = 30 },
                new FileNameRule { Token = @"ida32", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"ida64", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"idaw", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 70, Score = 24 },
                new FileNameRule { Token = @"idaw64", Category = @"File Name Scan", Label = @"IDA disassembler detected", Severity = Severity.Medium, Confidence = 70, Score = 24 },
                new FileNameRule { Token = @"hex rays", Category = @"File Name Scan", Label = @"Hex-Rays decompiler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"hexrays", Category = @"File Name Scan", Label = @"Hex-Rays decompiler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"ghidra", Category = @"File Name Scan", Label = @"Ghidra reverse-engineering suite detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"binary ninja", Category = @"File Name Scan", Label = @"Binary Ninja disassembler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"binaryninja", Category = @"File Name Scan", Label = @"Binary Ninja disassembler detected", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"radare2", Category = @"File Name Scan", Label = @"Radare2 reverse-engineering tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"cutter", Category = @"File Name Scan", Label = @"Cutter reverse-engineering tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"dnspy", Category = @"File Name Scan", Label = @".NET game decompilation tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"ilspy", Category = @"File Name Scan", Label = @".NET game decompilation tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"de4dot", Category = @"File Name Scan", Label = @".NET deobfuscation tool detected", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"reclass", Category = @"File Name Scan", Label = @"Memory/reversing tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"scylla", Category = @"File Name Scan", Label = @"Dumping/reversing tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"system informer", Category = @"File Name Scan", Label = @"System Informer process inspection tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"systeminformer", Category = @"File Name Scan", Label = @"System Informer process inspection tool detected", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"process hacker", Category = @"File Name Scan", Label = @"Process Hacker inspection tool detected", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"processhacker", Category = @"File Name Scan", Label = @"Process Hacker inspection tool detected", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"procexp", Category = @"File Name Scan", Label = @"Process Explorer detected", Severity = Severity.Low, Confidence = 45, Score = 6 },
            };
        }

        public static List<FileNameRule> InstalledProgramRules()
        {
            return new List<FileNameRule>
            {
                new FileNameRule { Token = @"cheat engine", Category = @"Installed Programs", Label = @"Cheat Engine memory editor installed", Severity = Severity.High, Confidence = 84, Score = 45 },
                new FileNameRule { Token = @"cheatengine", Category = @"Installed Programs", Label = @"Cheat Engine memory editor installed", Severity = Severity.High, Confidence = 84, Score = 45 },
                new FileNameRule { Token = @"wemod", Category = @"Installed Programs", Label = @"WeMod game trainer installed", Severity = Severity.High, Confidence = 80, Score = 38 },
                new FileNameRule { Token = @"ida", Category = @"Installed Programs", Label = @"IDA disassembler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"ida pro", Category = @"Installed Programs", Label = @"IDA disassembler installed", Severity = Severity.Low, Confidence = 64, Score = 12 },
                new FileNameRule { Token = @"ida64", Category = @"Installed Programs", Label = @"IDA disassembler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"hex rays", Category = @"Installed Programs", Label = @"Hex-Rays decompiler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"hexrays", Category = @"Installed Programs", Label = @"Hex-Rays decompiler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"ghidra", Category = @"Installed Programs", Label = @"Ghidra reverse-engineering suite installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"binary ninja", Category = @"Installed Programs", Label = @"Binary Ninja disassembler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"binaryninja", Category = @"Installed Programs", Label = @"Binary Ninja disassembler installed", Severity = Severity.Low, Confidence = 62, Score = 10 },
                new FileNameRule { Token = @"x64dbg", Category = @"Installed Programs", Label = @"Game debugging/disassembly tool installed", Severity = Severity.Low, Confidence = 60, Score = 8 },
                new FileNameRule { Token = @"x32dbg", Category = @"Installed Programs", Label = @"Game debugging/disassembly tool installed", Severity = Severity.Low, Confidence = 60, Score = 8 },
                new FileNameRule { Token = @"ollydbg", Category = @"Installed Programs", Label = @"Game debugging/disassembly tool installed", Severity = Severity.Low, Confidence = 60, Score = 8 },
                new FileNameRule { Token = @"dnspy", Category = @"Installed Programs", Label = @".NET decompilation tool installed", Severity = Severity.Low, Confidence = 60, Score = 8 },
                new FileNameRule { Token = @"ilspy", Category = @"Installed Programs", Label = @".NET decompilation tool installed", Severity = Severity.Low, Confidence = 60, Score = 8 },
                new FileNameRule { Token = @"de4dot", Category = @"Installed Programs", Label = @".NET deobfuscation tool installed", Severity = Severity.Low, Confidence = 58, Score = 6 },
                new FileNameRule { Token = @"reclass", Category = @"Installed Programs", Label = @"Memory/reversing tool installed", Severity = Severity.Low, Confidence = 58, Score = 6 },
                new FileNameRule { Token = @"scylla", Category = @"Installed Programs", Label = @"Dumping/reversing tool installed", Severity = Severity.Low, Confidence = 58, Score = 6 },
                new FileNameRule { Token = @"system informer", Category = @"Installed Programs", Label = @"System Informer process inspection tool installed", Severity = Severity.Low, Confidence = 55, Score = 5 },
                new FileNameRule { Token = @"systeminformer", Category = @"Installed Programs", Label = @"System Informer process inspection tool installed", Severity = Severity.Low, Confidence = 55, Score = 5 },
                new FileNameRule { Token = @"process hacker", Category = @"Installed Programs", Label = @"Process Hacker inspection tool installed", Severity = Severity.Low, Confidence = 55, Score = 5 },
                new FileNameRule { Token = @"processhacker", Category = @"Installed Programs", Label = @"Process Hacker inspection tool installed", Severity = Severity.Low, Confidence = 55, Score = 5 },
            };
        }

        public static List<FileNameRule> BrowserHistoryRules()
        {
            return new List<FileNameRule>
            {
                new FileNameRule { Token = @"unknowncheats", Category = @"Browser History", Label = @"Browser history shows known cheat forum/site", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"unknowncheats.me", Category = @"Browser History", Label = @"Browser history shows known cheat forum/site", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"guidedhacking", Category = @"Browser History", Label = @"Browser history shows game-hacking forum/site", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"guidedhacking.com", Category = @"Browser History", Label = @"Browser history shows game-hacking forum/site", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"elitepvpers.com", Category = @"Browser History", Label = @"Browser history shows cheat marketplace/forum domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"blackhatworld.com", Category = @"Browser History", Label = @"Browser history shows blackhat marketplace/forum domain", Severity = Severity.Medium, Confidence = 68, Score = 24 },
                new FileNameRule { Token = @"lethality.club", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"evicted.wtf", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"cheatprovider.store", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"burgercheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"team073.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"spyderrz.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"not-reversing.com", Category = @"Browser History", Label = @"Browser history shows reversing/cheat tooling domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"beaztcheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"suspectcheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"lexshop.xyz", Category = @"Browser History", Label = @"Browser history shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"shxdowcheats.net", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"ssz.gg", Category = @"Browser History", Label = @"Browser history shows cheat/service domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"apexdma.xyz", Category = @"Browser History", Label = @"Browser history shows DMA cheat/service domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"sapphire-service.shop", Category = @"Browser History", Label = @"Browser history shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"only-cheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"deprimereshop.com", Category = @"Browser History", Label = @"Browser history shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"kernaim.to", Category = @"Browser History", Label = @"Browser history shows kernel/aim cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"cosmocheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"disconnect.wtf", Category = @"Browser History", Label = @"Browser history shows cheat/service domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"disconnectcheats.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"mpgh.net", Category = @"Browser History", Label = @"Browser history shows game-hacking forum/site", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"aimjunkies.com", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"artificialaiming.net", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"klar.gg", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"phantomoverlay.io", Category = @"Browser History", Label = @"Browser history shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"cheats.com", Category = @"Browser History", Label = @"Browser history shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.net", Category = @"Browser History", Label = @"Browser history shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.gg", Category = @"Browser History", Label = @"Browser history shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.xyz", Category = @"Browser History", Label = @"Browser history shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheat.shop", Category = @"Browser History", Label = @"Browser history shows cheat-related shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheat.store", Category = @"Browser History", Label = @"Browser history shows cheat-related shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"aimbot", Category = @"Browser History", Label = @"Browser history shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"triggerbot", Category = @"Browser History", Label = @"Browser history shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"wallhack", Category = @"Browser History", Label = @"Browser history shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"ragebot", Category = @"Browser History", Label = @"Browser history shows cheat feature keyword", Severity = Severity.High, Confidence = 76, Score = 35 },
                new FileNameRule { Token = @"silent aim", Category = @"Browser History", Label = @"Browser history shows cheat feature keyword", Severity = Severity.High, Confidence = 75, Score = 35 },
                new FileNameRule { Token = @"cs2 cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"csgo cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"valorant cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"fortnite cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"warzone cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"apex cheat", Category = @"Browser History", Label = @"Browser history shows game cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"dma cheat", Category = @"Browser History", Label = @"Browser history shows DMA cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"kdmapper", Category = @"Browser History", Label = @"Browser history shows kernel driver mapper keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"driver mapper", Category = @"Browser History", Label = @"Browser history shows kernel driver mapper keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"manual map", Category = @"Browser History", Label = @"Browser history shows manual mapping keyword", Severity = Severity.Medium, Confidence = 65, Score = 22 },
                new FileNameRule { Token = @"eac bypass", Category = @"Browser History", Label = @"Browser history shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"battleye bypass", Category = @"Browser History", Label = @"Browser history shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"vanguard bypass", Category = @"Browser History", Label = @"Browser history shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"hwid spoofer", Category = @"Browser History", Label = @"Browser history shows hardware ID spoofer keyword", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"trace cleaner", Category = @"Browser History", Label = @"Browser history shows trace-cleaner keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"extreme injector", Category = @"Browser History", Label = @"Browser history shows injector keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"injector", Category = @"Browser History", Label = @"Browser history shows injector keyword", Severity = Severity.Medium, Confidence = 60, Score = 18 },
                new FileNameRule { Token = @"cheat engine", Category = @"Browser History", Label = @"Browser history shows Cheat Engine / memory editor keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheatengine", Category = @"Browser History", Label = @"Browser history shows Cheat Engine / memory editor keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"wemod", Category = @"Browser History", Label = @"Browser history shows WeMod game trainer keyword", Severity = Severity.High, Confidence = 76, Score = 35 },
                new FileNameRule { Token = @"ida pro", Category = @"Browser History", Label = @"Browser history shows IDA disassembler keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"ida64", Category = @"Browser History", Label = @"Browser history shows IDA disassembler keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"ghidra", Category = @"Browser History", Label = @"Browser history shows Ghidra reverse-engineering keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"binary ninja", Category = @"Browser History", Label = @"Browser history shows Binary Ninja disassembler keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"x64dbg", Category = @"Browser History", Label = @"Browser history shows debugger/disassembler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"dnspy", Category = @"Browser History", Label = @"Browser history shows .NET decompiler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"ilspy", Category = @"Browser History", Label = @"Browser history shows .NET decompiler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"system informer", Category = @"Browser History", Label = @"Browser history shows process inspection keyword", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"process hacker", Category = @"Browser History", Label = @"Browser history shows process inspection keyword", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"kmbox", Category = @"Browser History", Label = @"Browser history shows external input-assist tooling keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
            };
        }

        public static List<FileNameRule> ExecutionRules()
        {
            return new List<FileNameRule>
            {
                new FileNameRule { Token = @"kdmapper", Category = @"Execution Evidence", Label = @"Kernel driver mapper execution trace", Severity = Severity.High, Confidence = 86, Score = 55 },
                new FileNameRule { Token = @"driver mapper", Category = @"Execution Evidence", Label = @"Kernel driver mapper execution trace", Severity = Severity.High, Confidence = 82, Score = 48 },
                new FileNameRule { Token = @"manual map", Category = @"Execution Evidence", Label = @"Manual-mapping execution trace", Severity = Severity.High, Confidence = 78, Score = 42 },
                new FileNameRule { Token = @"cheat engine", Category = @"Execution Evidence", Label = @"Cheat Engine execution trace", Severity = Severity.High, Confidence = 84, Score = 50 },
                new FileNameRule { Token = @"cheatengine", Category = @"Execution Evidence", Label = @"Cheat Engine execution trace", Severity = Severity.High, Confidence = 84, Score = 50 },
                new FileNameRule { Token = @"extreme injector", Category = @"Execution Evidence", Label = @"Extreme Injector execution trace", Severity = Severity.High, Confidence = 84, Score = 50 },
                new FileNameRule { Token = @"injector", Category = @"Execution Evidence", Label = @"Injector execution trace", Severity = Severity.Medium, Confidence = 68, Score = 30 },
                new FileNameRule { Token = @"wemod", Category = @"Execution Evidence", Label = @"WeMod/trainer execution trace", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"ida64", Category = @"Execution Evidence", Label = @"IDA disassembler execution trace", Severity = Severity.Medium, Confidence = 74, Score = 32 },
                new FileNameRule { Token = @"ida", Category = @"Execution Evidence", Label = @"IDA disassembler execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"hex rays", Category = @"Execution Evidence", Label = @"Hex-Rays decompiler execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"ghidra", Category = @"Execution Evidence", Label = @"Ghidra reverse-engineering execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"binary ninja", Category = @"Execution Evidence", Label = @"Binary Ninja execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"x64dbg", Category = @"Execution Evidence", Label = @"x64dbg debugger execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"x32dbg", Category = @"Execution Evidence", Label = @"x32dbg debugger execution trace", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"ollydbg", Category = @"Execution Evidence", Label = @"OllyDbg debugger execution trace", Severity = Severity.Medium, Confidence = 70, Score = 26 },
                new FileNameRule { Token = @"dnspy", Category = @"Execution Evidence", Label = @"dnSpy decompiler execution trace", Severity = Severity.Medium, Confidence = 70, Score = 26 },
                new FileNameRule { Token = @"ilspy", Category = @"Execution Evidence", Label = @"ILSpy decompiler execution trace", Severity = Severity.Medium, Confidence = 68, Score = 24 },
                new FileNameRule { Token = @"reclass", Category = @"Execution Evidence", Label = @"ReClass memory/reversing execution trace", Severity = Severity.Medium, Confidence = 68, Score = 24 },
                new FileNameRule { Token = @"system informer", Category = @"Execution Evidence", Label = @"System Informer process-inspection execution trace", Severity = Severity.Medium, Confidence = 66, Score = 22 },
                new FileNameRule { Token = @"process hacker", Category = @"Execution Evidence", Label = @"Process Hacker process-inspection execution trace", Severity = Severity.Medium, Confidence = 64, Score = 20 },
                new FileNameRule { Token = @"hwid spoofer", Category = @"Execution Evidence", Label = @"HWID spoofer execution trace", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"spoofer", Category = @"Execution Evidence", Label = @"Spoofer execution trace", Severity = Severity.Medium, Confidence = 66, Score = 26 },
                new FileNameRule { Token = @"trace cleaner", Category = @"Execution Evidence", Label = @"Trace-cleaner execution trace", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"aimbot", Category = @"Execution Evidence", Label = @"Cheat feature execution trace", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"triggerbot", Category = @"Execution Evidence", Label = @"Cheat feature execution trace", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"ragebot", Category = @"Execution Evidence", Label = @"Cheat feature execution trace", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"silent aim", Category = @"Execution Evidence", Label = @"Cheat feature execution trace", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"wallhack", Category = @"Execution Evidence", Label = @"Cheat feature execution trace", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"bypass", Category = @"Execution Evidence", Label = @"Anti-cheat bypass execution trace", Severity = Severity.Medium, Confidence = 66, Score = 28 },
            };
        }

        public static List<FileNameRule> BrowserDownloadRules()
        {
            return new List<FileNameRule>
            {
                new FileNameRule { Token = @"unknowncheats", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows known cheat forum/site", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"unknowncheats.me", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows known cheat forum/site", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"guidedhacking", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game-hacking forum/site", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"guidedhacking.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game-hacking forum/site", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"elitepvpers.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat marketplace/forum domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"blackhatworld.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows blackhat marketplace/forum domain", Severity = Severity.Medium, Confidence = 68, Score = 24 },
                new FileNameRule { Token = @"lethality.club", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"evicted.wtf", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"cheatprovider.store", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"burgercheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"team073.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"spyderrz.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"not-reversing.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows reversing/cheat tooling domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"beaztcheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"suspectcheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"lexshop.xyz", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"shxdowcheats.net", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"ssz.gg", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat/service domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"apexdma.xyz", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows DMA cheat/service domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"sapphire-service.shop", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"only-cheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"deprimereshop.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat/service shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"kernaim.to", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows kernel/aim cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"cosmocheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"disconnect.wtf", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat/service domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"disconnectcheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 84, Score = 48 },
                new FileNameRule { Token = @"mpgh.net", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game-hacking forum/site", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"aimjunkies.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"artificialaiming.net", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"klar.gg", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"phantomoverlay.io", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat provider domain", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"cheats.com", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.net", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.gg", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheats.xyz", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related domain wording", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheat.shop", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheat.store", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat-related shop domain", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"aimbot", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"triggerbot", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"wallhack", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat feature keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"ragebot", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat feature keyword", Severity = Severity.High, Confidence = 76, Score = 35 },
                new FileNameRule { Token = @"silent aim", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows cheat feature keyword", Severity = Severity.High, Confidence = 75, Score = 35 },
                new FileNameRule { Token = @"cs2 cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"csgo cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"valorant cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"fortnite cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 80, Score = 42 },
                new FileNameRule { Token = @"warzone cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"apex cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows game cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"dma cheat", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows DMA cheat keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"kdmapper", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows kernel driver mapper keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"driver mapper", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows kernel driver mapper keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"manual map", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows manual mapping keyword", Severity = Severity.Medium, Confidence = 65, Score = 22 },
                new FileNameRule { Token = @"eac bypass", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"battleye bypass", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"vanguard bypass", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows anti-cheat bypass keyword", Severity = Severity.High, Confidence = 82, Score = 45 },
                new FileNameRule { Token = @"hwid spoofer", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows hardware ID spoofer keyword", Severity = Severity.Medium, Confidence = 72, Score = 28 },
                new FileNameRule { Token = @"trace cleaner", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows trace-cleaner keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"extreme injector", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows injector keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"injector", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows injector keyword", Severity = Severity.Medium, Confidence = 60, Score = 18 },
                new FileNameRule { Token = @"cheat engine", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows Cheat Engine / memory editor keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"cheatengine", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows Cheat Engine / memory editor keyword", Severity = Severity.High, Confidence = 78, Score = 38 },
                new FileNameRule { Token = @"wemod", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows WeMod game trainer keyword", Severity = Severity.High, Confidence = 76, Score = 35 },
                new FileNameRule { Token = @"ida pro", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows IDA disassembler keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"ida64", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows IDA disassembler keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"ghidra", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows Ghidra reverse-engineering keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"binary ninja", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows Binary Ninja disassembler keyword", Severity = Severity.Medium, Confidence = 68, Score = 22 },
                new FileNameRule { Token = @"x64dbg", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows debugger/disassembler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"dnspy", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows .NET decompiler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"ilspy", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows .NET decompiler keyword", Severity = Severity.Medium, Confidence = 65, Score = 20 },
                new FileNameRule { Token = @"system informer", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows process inspection keyword", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"process hacker", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows process inspection keyword", Severity = Severity.Medium, Confidence = 62, Score = 18 },
                new FileNameRule { Token = @"kmbox", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record shows external input-assist tooling keyword", Severity = Severity.Medium, Confidence = 70, Score = 25 },
                new FileNameRule { Token = @"loader", Category = @"Browser Source/Download Evidence", Label = @"Browser source/download record for loader/tooling", Severity = Severity.Medium, Confidence = 62, Score = 22 },
            };
        }

    }
}